



insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Novi Sad', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 1')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Sabac', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 2')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Nis', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 3')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Beograd', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 4')


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic1@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic2@gmail.com', true, 'Nemanja', 'kinzo','+381613238249', 'Tamic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic3@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Ivanovic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic4@gmail.com', true, 'Ana', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic5@gmail.com', true, 'Milica', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic6@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic7@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Lakic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic8@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Loncar', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic9@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Vulin', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic10@gmail.com', true, 'Mirko', 'kinzo','+381613238249', 'Milinkovic', 'DERMATOLOGIST', null, null)

insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,1)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,2)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,3)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,4)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,5)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,6)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,7)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,8)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,9)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (4,10)


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic11@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Savic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic12@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Markovic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic13@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Jovanovic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic14@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Matejic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic15@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Preradovic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic16@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Prpic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic17@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic18@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Atanasijevic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic19@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonijevic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic20@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 4)



insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic21@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic22@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic23@gmail.com', true, 'Petar', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic24@gmail.com', true, 'Perica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic25@gmail.com', true, 'Milic', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic26@gmail.com', true, 'Sandra', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic27@gmail.com', true, 'Tamara', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic28@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic29@gmail.com', true, 'Jelena', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic30@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic31@gmail.com', true, 'Nenad', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic32@gmail.com', true, 'Katarina', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic33@gmail.com', true, 'Dusan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic34@gmail.com', true, 'Stevan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic35@gmail.com', true, 'Konjislav', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic36@gmail.com', true, 'Boban', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic37@gmail.com', true, 'Mikica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic38@gmail.com', true, 'Izet', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic39@gmail.com', true, 'Farok', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic40@gmail.com', true, 'Radasin', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)


insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Brufen', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Panklav', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Phlebodia', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Synthroid', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Crestor', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Nexium', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Abilify', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Crestor', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Lantus Solostar', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Advair Diskus', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Remicade', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Lisinopril', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Levothyroxine', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Metoprolol', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Omeprazole', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Simvastatin', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Losartan', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Albuterol', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Sirup', 'NA_RECEPT', '', '', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('', '', '', 'MedbayTech', 'PRASAK', 'Panklav', 'NA_RECEPT', '', '', 'ANTIPYRETIC')


insert into medication_quantity (quantity, medication_id) values (10, 1)
insert into medication_quantity (quantity, medication_id) values (10, 2)
insert into medication_quantity (quantity, medication_id) values (10, 3)
insert into medication_quantity (quantity, medication_id) values (10, 4)
insert into medication_quantity (quantity, medication_id) values (10, 5)
insert into medication_quantity (quantity, medication_id) values (10, 6)
insert into medication_quantity (quantity, medication_id) values (10, 7)
insert into medication_quantity (quantity, medication_id) values (10, 8)
insert into medication_quantity (quantity, medication_id) values (10, 9)
insert into medication_quantity (quantity, medication_id) values (10, 10)
insert into medication_quantity (quantity, medication_id) values (10, 11)
insert into medication_quantity (quantity, medication_id) values (10, 12)
insert into medication_quantity (quantity, medication_id) values (10, 13)
insert into medication_quantity (quantity, medication_id) values (10, 14)
insert into medication_quantity (quantity, medication_id) values (10, 15)
insert into medication_quantity (quantity, medication_id) values (10, 16)
insert into medication_quantity (quantity, medication_id) values (10, 17)
insert into medication_quantity (quantity, medication_id) values (10, 18)
insert into medication_quantity (quantity, medication_id) values (10, 19)
insert into medication_quantity (quantity, medication_id) values (10, 20)

insert into medication_quantity (quantity, medication_id) values (4, 1)
insert into medication_quantity (quantity, medication_id) values (4, 2)
insert into medication_quantity (quantity, medication_id) values (4, 3)
insert into medication_quantity (quantity, medication_id) values (4, 4)
insert into medication_quantity (quantity, medication_id) values (4, 5)
insert into medication_quantity (quantity, medication_id) values (4, 6)
insert into medication_quantity (quantity, medication_id) values (4, 7)
insert into medication_quantity (quantity, medication_id) values (4, 8)
insert into medication_quantity (quantity, medication_id) values (4, 9)
insert into medication_quantity (quantity, medication_id) values (4, 10)
insert into medication_quantity (quantity, medication_id) values (4, 11)
insert into medication_quantity (quantity, medication_id) values (4, 12)
insert into medication_quantity (quantity, medication_id) values (4, 13)

insert into patient_allerged_on_medications(patient_id, medication_id) values (21, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (21, 2)
insert into patient_allerged_on_medications(patient_id, medication_id) values (21, 3)
insert into patient_allerged_on_medications(patient_id, medication_id) values (21, 4)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 2)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 3)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 4)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 18)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 19)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 15)

--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 21, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 22, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 23, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 24, 2)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 25, 2)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 26, 2)
--
--
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,36)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,37)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (2,38)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (2,39)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (3,40)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (3,41)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (4,42)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (4,43)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (5,44)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (5,45)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (6,46)


insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,20)

insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,4)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (10,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (10,1)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,2)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,13)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,1)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,13)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,5)

--insert into replacement_medications (medication_id, replacement_medication_id) values (1,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,4)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (10,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (10,1)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,2)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,13)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,1)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,13)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,5)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, 'SN1345', '2021-06-30 00:00:00-08', '2021-06-01 00:00:00-08', 1,21,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, 'SN1315', '2021-06-30 00:00:00-08', '2021-06-01 00:00:00-08', 2,22,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, 'SN1245', '2021-06-09 00:00:00-08', '2021-06-03 00:00:00-08', 3,23,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, 'SN1465', '2021-06-05 00:00:00-08', '2021-06-03 00:00:00-08', 4,24,1)

--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 5,25,2)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 6,26,2)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 7,27,2)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 8,28,2)
--
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 9,29,3)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 10,30,3)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 11,31,3)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 12,32,3)
--
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 13,33,4)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 14,34,4)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 15,35,4)
--insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 16,36,4)

insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-14 14:00:00-08', '2021-06-14 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-15 14:00:00-08', '2021-06-15 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-16 14:00:00-08', '2021-06-16 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-17 14:00:00-08', '2021-06-17 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-18 22:00:00-08', '2021-06-18 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-19 22:00:00-08', '2021-06-19 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-20 22:00:00-08', '2021-06-20 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-21 22:00:00-08', '2021-06-21 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-22 22:00:00-08', '2021-06-22 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 07:00:00-08', 1)

insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-14 14:00:00-08', '2021-06-14 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-15 14:00:00-08', '2021-06-15 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-16 14:00:00-08', '2021-06-16 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-17 14:00:00-08', '2021-06-17 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-18 22:00:00-08', '2021-06-18 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-19 22:00:00-08', '2021-06-19 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-20 22:00:00-08', '2021-06-20 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-21 22:00:00-08', '2021-06-21 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-22 22:00:00-08', '2021-06-22 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 07:00:00-08', 11)
--
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 11)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 12)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 13)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 14)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 15)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 16)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 17)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 18)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 19)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 20)



insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', 1, 21, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', 1, 23, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 11:30:00-08', '2021-06-13 11:00:00-08', '', 1, 24, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 12:00:00-08', '2021-06-13 11:30:00-08', '', 1, 25, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 12:30:00-08', '2021-06-13 12:00:00-08', '', 1, 26, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 13:00:00-08', '2021-06-13 12:30:00-08', '', 1, 27, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 13:30:00-08', '2021-06-13 13:00:00-08', '', 1, 21, 1)

insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 11:30:00-08', '2021-07-13 11:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 12:00:00-08', '2021-07-13 11:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 12:30:00-08', '2021-07-13 12:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-08-13 13:00:00-08', '2021-08-13 12:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-08-13 13:30:00-08', '2021-08-13 13:00:00-08', '', null, null, 1)


insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', 22, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', 23, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', 24, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 11:30:00-08', '2021-06-13 11:00:00-08', '', 25, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 12:00:00-08', '2021-06-13 11:30:00-08', '', 26, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 12:30:00-08', '2021-06-13 12:00:00-08', '', 27, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 13:00:00-08', '2021-06-13 12:30:00-08', '', 28, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 13:30:00-08', '2021-06-13 13:00:00-08', '', 29, 11, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 14:00:00-08', '2021-06-13 13:30:00-08', '', 22, 11, 1)


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacy_admin', 'Novi Sad', '23', 21242, 'Srbija', 'Stefana Nemanje1', 'pjevalica@gmail.com', true, 'Bojana', 'bobi','+381613238240', 'Pjevalica', 'PHARMACY_ADMINISTRATOR', null, 1)


insert into absences(is_approved, is_finished, endtime, starttime, user_id) values (true, false, '2021-07-20 00:00:00-08', '2021-07-10 00:00:00-08', 1)