
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Novi Sad', '10', 21000, 'Srbija', 'Dragomira Radukina', 9, 'Pharmacy 1')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Sabac', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 2')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Nis', '8', 25000, 'Srbija', 'Nikole Tesle', 9, 'Pharmacy 3')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Beograd', '1', 23220, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 4')

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic1@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic2@gmail.com', true, 'Nemanja', 'kinzo','+381613238249', 'Tamic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic3@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Ivanovic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic4@gmail.com', true, 'Ana', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic5@gmail.com', true, 'Milica', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic6@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic7@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Lakic', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic8@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Loncar', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic9@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Vulin', 'DERMATOLOGIST', null, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic10@gmail.com', true, 'Mirko', 'kinzo','+381613238249', 'Milinkovic', 'DERMATOLOGIST', null, null)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('System_admin', 'Novi Sad', '23', 21000, 'Srbija', 'Stefana Nemanje', 'joksi1@gmail.com', true, 'Jovana', 'joksi','+381613238249', 'Jakovljevic', 'SYSTEM_ADMINISTRATOR', null, null)

insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,1)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,2)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,10)

insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,3)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,4)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,5)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,6)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,7)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,8)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,9)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (4,10)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic11@gmail.com', true, 'Marko', 'kinzo','+381613238249', 'Savic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic12@gmail.com', true, 'Marko', 'kinzo','+381613238249', 'Markovic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic13@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Jovanovic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic14@gmail.com', true, 'Mateja', 'kinzo','+381613238249', 'Matejic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic15@gmail.com', true, 'Prerad', 'kinzo','+381613238249', 'Preradovic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic16@gmail.com', true, 'Prerad', 'kinzo','+381613238249', 'Prpic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic17@gmail.com', true, 'Anton', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic18@gmail.com', true, 'Atanasije', 'kinzo','+381613238249', 'Atanasijevic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic19@gmail.com', true, 'Antonije', 'kinzo','+381613238249', 'Antonijevic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic20@gmail.com', true, 'Andrej', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 4)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic21@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null) 
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic22@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic23@gmail.com', true, 'Petar', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic24@gmail.com', true, 'Perica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic25@gmail.com', true, 'Milic', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic26@gmail.com', true, 'Sandra', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic27@gmail.com', true, 'Tamara', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic28@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic29@gmail.com', true, 'Jelena', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic30@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic31@gmail.com', true, 'Nenad', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic32@gmail.com', true, 'Katarina', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic33@gmail.com', true, 'Dusan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic34@gmail.com', true, 'Stevan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic35@gmail.com', true, 'Konjislav', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic36@gmail.com', true, 'Boban', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic37@gmail.com', true, 'Mikica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic38@gmail.com', true, 'Izet', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic39@gmail.com', true, 'Farok', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic40@gmail.com', true, 'Radasin', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 11444,'Srbija', 'Stefana Nemanje', 'sweetbee0071@gmail.com', true, 'Bole', 'boki','+381613238249', 'Pj', 'PATIENT', 0, null)


insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1002', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'MedbayTech', 'TABLETA', 'Brufen', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1003', 'Moguca pojava mucnine.', 'Lek nije namenjen za trudnice.', 'MedbayTech', 'PRASAK', 'Panklav', 'BEZ_RECEPTA', '3x1', 'Paracetamol; kofein', 'HORMONE')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1004', 'Nema.', 'Za decu.', 'IrisPharm', 'KAPSULA', 'Phlebodia', 'BEZ_RECEPTA', '3x1', 'diklofenak-kalijum', 'PROBIOTIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1005', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'Biopharma', 'PRASAK', 'Synthroid', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1006', 'Moguca pojava mucnine.', 'Lek nije namenjen za trudnice.', 'MedbayTech', 'SIRUP', 'Crestor', 'NA_RECEPT', '3x1', 'diklofenak-kalijum', 'TRANQUILIZER')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1007', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'Biopharma', 'TABLETA', 'Nexium', 'NA_RECEPT', '3x1', 'Paracetamol; kofein; saharoza; talk', 'PROBIOTIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1008', 'Nema.', 'Lek nije namenjen za trudnice.', 'MedbayTech', 'KAPSULA', 'Abilify', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1009', 'Nema.', 'Lek je namenjen za osobe starije od 12god.', 'IrisPharm', 'SIRUP', 'Crestor', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'HORMONE')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1010', 'Nema.', 'Lek je namenjen za osobe starije od 12god.', 'Biopharma', 'PRASAK', 'Lantus Solostar', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'TRANQUILIZER')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1011', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'IrisPharm', 'PRASAK', 'Advair Diskus', 'NA_RECEPT', '3x1', 'Paracetamol; kofein', 'PROBIOTIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1012', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'MedbayTech', 'TABLETA', 'Remicade', 'BEZ_RECEPTA', '3x1', 'Magnezijum-stearat; saharoza; talk', 'HORMONE')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1013', 'Moguca pojava mucnine.', 'Za decu.', 'MedbayTech', 'KAPSULA', 'Lisinopril', 'NA_RECEPT', '3x1', 'Magnezijum-stearat; saharoza; talk', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1014', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'IrisPharm', 'PRASAK', 'Levothyroxine', 'NA_RECEPT', '3x1', 'Paracetamol; kofein', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1015', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'MedbayTech', 'SIRUP', 'Metoprolol', 'BEZ_RECEPTA', '3x1', 'Magnezijum-stearat', 'HORMONE')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1016', 'Moguca pojava mucnine.', 'Za decu.', 'MedbayTech', 'PRASAK', 'Omeprazole', 'NA_RECEPT', '3x1', 'diklofenak-kalijum', 'PROBIOTIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1017', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'Biopharma', 'TABLETA', 'Simvastatin', 'NA_RECEPT', '3x1', 'diklofenak-kalijum', 'TRANQUILIZER')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1018', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'MedbayTech', 'KAPSULA', 'Losartan', 'BEZ_RECEPTA', '3x1', 'Paracetamol; kofein', 'HORMONE')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1019', 'Moguca pojava mucnine.', 'Za decu.', 'Biopharma', 'TABLETA', 'Albuterol', 'NA_RECEPT', '3x1', 'Paracetamol; kofein', 'ANTIPYRETIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1020', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'MedbayTech', 'PRASAK', 'Sirup', 'BEZ_RECEPTA', '3x1', 'Magnezijum-stearat; saharoza; talk', 'PROBIOTIC')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type) values ('1021', 'Moguca pojava mucnine.', 'Lek je namenjen za osobe starije od 12god.', 'IrisPharm', 'SIRUP', 'Panklav2', 'NA_RECEPT', '3x1', 'diklofenak-kalijum', 'TRANQUILIZER')


insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 1,1)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (20, 5,1)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 6,1)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 4,1)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 2,1)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 3,1)



insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 1,2)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (20, 5,2)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 6,2)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 4,2)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 2,2)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 3,2)



insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 1,3)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (20, 5,3)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 6,3)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 4,3)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 2,3)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 3,3)



insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 1,4)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (20, 5,4)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 6,4)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 4,4)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 2,4)
insert into medication_quantity (quantity, medication_id,pharmacy_id) values (10, 3,4)


insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (22, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (23, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (24, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (25, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (26, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (27, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (28, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (29, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (30, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (31, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 2)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 3)
insert into patient_allerged_on_medications(patient_id, medication_id) values (32, 4)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (33, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 18)
insert into patient_allerged_on_medications(patient_id, medication_id) values (34, 19)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (35, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (36, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (37, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (38, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (39, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (40, 15)

--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 21, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 22, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 23, 1)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 24, 2)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 25, 2)
--insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 26, 2)
--
--
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,36)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,37)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (2,38)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (2,39)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (3,40)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (3,41)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (4,42)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (4,43)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (5,44)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (5,45)
--insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (6,46)




insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (1,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (2,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (3,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (4,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (5,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,4)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (6,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (7,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (8,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,11)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (9,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (10,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (10,1)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,2)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (11,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,13)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (12,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (13,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,1)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (14,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,14)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (15,16)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (16,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,6)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (17,10)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,13)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (18,5)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,7)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,18)
insert into medications_replacement_medications (medication_id, replacement_medications_id) values (19,5)

--insert into replacement_medications (medication_id, replacement_medication_id) values (1,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (1,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (2,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (3,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (4,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (5,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,4)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (6,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (7,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (8,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,11)
--insert into replacement_medications (medication_id, replacement_medication_id) values (9,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (10,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (10,1)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,2)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (11,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,13)
--insert into replacement_medications (medication_id, replacement_medication_id) values (12,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (13,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,1)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (14,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,14)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (15,16)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (16,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,6)
--insert into replacement_medications (medication_id, replacement_medication_id) values (17,10)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,13)
--insert into replacement_medications (medication_id, replacement_medication_id) values (18,5)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,7)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,18)
--insert into replacement_medications (medication_id, replacement_medication_id) values (19,5)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1315', '2021-06-30 00:00:00-08', '2021-06-01 00:00:00-08', 2,22,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1245', '2021-06-09 00:00:00-08', '2021-06-03 00:00:00-08', 3,23,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1465', '2021-06-05 00:00:00-08', '2021-06-03 00:00:00-08', 4,24,1)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, 'SN1465', '2021-06-05 00:00:00-08', '2021-06-03 00:00:00-08', 6,24,1)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-08-01 00:00:00-08', '2021-09-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-08-01 00:00:00-08', '2021-09-01 00:00:00-08', 1,22,4)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-02-01 00:00:00-08', '2021-02-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-02-01 00:00:00-08', '2021-02-01 00:00:00-08', 1,22,4)


insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,2)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,4)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,2)


insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,3)


insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,4)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-08-01 00:00:00-08', '2021-08-01 00:00:00-08', 1,22,2)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-08-01 00:00:00-08', '2021-08-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-08-01 00:00:00-08', '2021-08-01 00:00:00-08', 1,22,4)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-09-01 00:00:00-08', '2021-09-01 00:00:00-08', 1,22,2)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-09-01 00:00:00-08', '2021-09-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-09-01 00:00:00-08', '2021-09-01 00:00:00-08', 1,22,4)

insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-02-01 00:00:00-08', '2021-02-01 00:00:00-08', 1,22,2)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-02-01 00:00:00-08', '2021-02-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-02-01 00:00:00-08', '2021-02-01 00:00:00-08', 1,22,4)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,2)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,3)
insert into reservations (is_done, serialnumber, endtime, starttime, medication_id, patient_id, pharmacy_id) values (true, 'SN1345', '2021-07-01 00:00:00-08', '2021-07-01 00:00:00-08', 1,22,4)



insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-14 14:00:00-08', '2021-06-14 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-15 14:00:00-08', '2021-06-15 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-16 14:00:00-08', '2021-06-16 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-17 14:00:00-08', '2021-06-17 07:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-18 22:00:00-08', '2021-06-18 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-19 22:00:00-08', '2021-06-19 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-20 22:00:00-08', '2021-06-20 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-21 22:00:00-08', '2021-06-21 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-06-22 22:00:00-08', '2021-06-22 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 07:00:00-08', 1)

insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-14 14:00:00-08', '2021-06-14 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-15 14:00:00-08', '2021-06-15 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-16 14:00:00-08', '2021-06-16 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-17 14:00:00-08', '2021-06-17 07:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-18 22:00:00-08', '2021-06-18 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-19 22:00:00-08', '2021-06-19 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-20 22:00:00-08', '2021-06-20 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-21 22:00:00-08', '2021-06-21 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-06-22 22:00:00-08', '2021-06-22 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 07:00:00-08', 11)
--
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 11)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 12)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 13)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 14)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 07:00:00-08', '2021-06-13 14:00:00-08', 15)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 16)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 17)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 18)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 19)
--insert into workdays (endtime, starttime, user_id) values ('2021-06-13 14:00:00-08', '2021-06-13 22:00:00-08', 20)



insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-13 10:00:00-08', '2021-05-13 09:30:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-13 10:00:00-08', '2021-05-13 09:30:00-08', '', 10, 22, 4)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-04-13 10:00:00-08', '2021-04-13 09:30:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', 1, 23, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 11:30:00-08', '2021-06-13 11:00:00-08', '', 1, 24, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 12:00:00-08', '2021-06-13 11:30:00-08', '', 1, 25, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 12:30:00-08', '2021-06-13 12:00:00-08', '', 1, 26, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, true, '2021-06-13 13:00:00-08', '2021-06-13 12:30:00-08', '', 1, 27, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-01-13 13:00:00-08', '2021-01-13 12:30:00-08', '', 2, 27, 1)

insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-04-13 13:30:00-08', '2021-04-13 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-10 13:30:00-08', '2021-05-10 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-06-10 13:30:00-08', '2021-06-10 13:00:00-08', '', 1, 22, 1)


insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-02-13 13:30:00-08', '2021-02-13 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-03-10 13:30:00-08', '2021-03-10 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-04-10 13:30:00-08', '2021-04-10 13:00:00-08', '', 1, 22, 1)


insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-13 13:30:00-08', '2021-05-13 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-06-12 13:30:00-08', '2021-06-12 13:00:00-08', '', 1, 22, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-09-10 13:30:00-08', '2021-09-10 13:00:00-08', '', 1, 22, 1)


insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-04-13 13:30:00-08', '2021-04-13 13:00:00-08', '', 2, 22, 2)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-10 13:30:00-08', '2021-05-10 13:00:00-08', '', 2, 22, 2)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-06-10 13:30:00-08', '2021-06-10 13:00:00-08', '', 2, 22, 2)

insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-04-13 13:30:00-08', '2021-04-13 13:00:00-08', '', 7, 22, 3)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-05-10 13:30:00-08', '2021-05-10 13:00:00-08', '', 7, 22, 3)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (true, true, '2021-06-10 13:30:00-08', '2021-06-10 13:00:00-08', '', 7, 22, 3)





insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 11:30:00-08', '2021-07-13 11:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 12:00:00-08', '2021-07-13 11:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 12:30:00-08', '2021-07-13 12:00:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-08-13 13:00:00-08', '2021-08-13 12:30:00-08', '', null, null, 1)
insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-08-13 13:30:00-08', '2021-08-13 13:00:00-08', '', null, null, 1)




insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 10:00:00-08', '2021-06-13 09:30:00-08', '', 22, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 10:30:00-08', '2021-06-13 10:00:00-08', '', 23, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 11:00:00-08', '2021-06-13 10:30:00-08', '', 24, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 11:30:00-08', '2021-06-13 11:00:00-08', '', 25, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 12:00:00-08', '2021-06-13 11:30:00-08', '', 26, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 12:30:00-08', '2021-06-13 12:00:00-08', '', 27, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 13:00:00-08', '2021-06-13 12:30:00-08', '', 28, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 13:30:00-08', '2021-06-13 13:00:00-08', '', 29, 12, 1)
insert into consultations (is_finished, is_taken, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, false, '2021-06-13 14:00:00-08', '2021-06-13 13:30:00-08', '', 22, 12, 1)


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacy_admin', 'Novi Sad', '23', 21242, 'Srbija', 'Stefana Nemanje1', 'pjevalica@gmail.com', true, 'Bojana', 'bobi','+381613238240', 'Pjevalica', 'PHARMACY_ADMINISTRATOR', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacy_admin', 'Novi Sad', '23', 21245, 'Srbija', 'Stefana Nemanje1', 'sara@gmail.com', true, 'Sara', 'admin','+381613238249', 'Jovic', 'PHARMACY_ADMINISTRATOR', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacy_admin', 'Novi Sad', '23', 21249, 'Srbija', 'Stefana Nemanje1', 'jovan@gmail.com', true, 'Jovan', 'admin','+381613238243', 'Jovic', 'PHARMACY_ADMINISTRATOR', null, 1)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('System_admin', 'Novi Sad', '1', 21000, 'Srbija', 'Dragomira Radukina', 'joksi1@gmail.com', true, 'Jovana', 'joksi','+381613238240', 'Jakovljevic', 'SYSTEM_ADMINISTRATOR', null, 1)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Supplier', 'Novi Sad', '1', 21000, 'Srbija', 'Dragomira Radukina', 'joksi2@gmail.com', true, 'Jovana', 'joksi','+381613238240', 'Jakovljevic', 'SUPPLIER', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Supplier', 'Novi Sad', '2', 21000, 'Srbija', 'Dragomira Radukina', 'joksi3@gmail.com', true, 'Jana', 'joksi','+381613238249', 'Jovic', 'SUPPLIER', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Supplier', 'Novi Sad', '3', 21000, 'Srbija', 'Dragomira Radukina', 'joksi4@gmail.com', true, 'Janko', 'joksi','+381613238243', 'Janjic', 'SUPPLIER', null, 3)

insert into pharmacies_subscribers(pharmacy_id,subscribers_id) values(1,41)
insert into absences( endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ( '2021-08-08',true, false, '2021-11-08','APPROVED', 1,11)

insert into absences(  endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ( '2021-08-08',false, false, '2021-08-15','PROCESSING', 1,12)
insert into absences(  endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ( '2021-08-08',false, false, '2021-08-15','PROCESSING', 1,13)
insert into absences( endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ('2021-08-08',false, false, '2021-08-08','PROCESSING', 2,14)

insert into absences( endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ('2021-08-08',false, false,  '2021-10-08','PROCESSING', 3,17)
insert into absences( endtime,is_approved,is_finished, starttime,type,pharmacy_id ,user_id) values ( '2021-08-08',false, false, '2021-08-08','PROCESSING',4,20)


--insert into purchase_order_list(endtime,purchase_status,starttime,pharmacy_administrator_id,pharmacy_id) values('2021-08-08','CEKA_PONUDE','2021-01-01',43,1)
--insert into medication_quantity_of_purchase_order(quantity,medication_id) values (10,1)
--insert into purchase_order_list_quantity_medications_purchase(purchase_order_id,quantity_medications_purchase_id) values(1,1)

--insert into purchase_order_list(endtime,purchase_status,starttime,pharmacy_administrator_id,pharmacy_id) values('2021-08-08','CEKA_PONUDE','2021-01-01',43,1)
--insert into medication_quantity_of_purchase_order(quantity,medication_id) values (10,2)
--insert into purchase_order_list_quantity_medications_purchase(purchase_order_id,quantity_medications_purchase_id) values(2,2)

--insert into purchase_order_list(endtime,purchase_status,starttime,pharmacy_administrator_id,pharmacy_id) values('2021-08-08','CEKA_PONUDE','2021-01-01',44,1)
--insert into medication_quantity_of_purchase_order(quantity,medication_id) values (10,3)
---insert into purchase_order_list_quantity_medications_purchase(purchase_order_id,quantity_medications_purchase_id) values(3,3)


insert into providers(name,email,info) values('Dobavljac 1','boyanasixxhalliwell@gmail.com','Najbolji dobavljac na svetu')
insert into providers(name,email,info) values('Dobavljac 2','blabla@gmail.com','Ekstra cene pun kvalitet')
insert into providers(name,email,info) values('Dobavljac 3','boyanacroft@yahoo.com','Lek za stek')

--insert into offers(status,price,purchase_order_id, provider_id) values ('CEKA',200,1,1)
--insert into offers(status,price,purchase_order_id,provider_id) values ('CEKA',150,1,2)
--insert into offers(status,price,purchase_order_id,provider_id) values ('CEKA',150,1,3)


insert into price_list_medications(status,start_time,pharmacy_id) values ('ACTIVE','2021-08-28 00:00:00-08',1)
insert into price_list_medications(status,start_time,pharmacy_id) values ('ACTIVE','2021-08-28 00:00:00-08',2)
insert into price_list_medications(status,start_time,pharmacy_id) values ('ACTIVE','2021-08-28 00:00:00-08',3)
insert into price_list_medications(status,start_time,pharmacy_id) values ('ACTIVE','2021-08-28 00:00:00-08',4)

insert into price_medications(price,medication_id,price_list_medication_id) values(220,1,1)
insert into price_medications(price,medication_id,price_list_medication_id) values(400,2,1)
insert into price_medications(price,medication_id,price_list_medication_id) values(300,3,1)
insert into price_medications(price,medication_id,price_list_medication_id) values(150,4,1)
insert into price_medications(price,medication_id,price_list_medication_id) values(100,5,1)
insert into price_medications(price,medication_id,price_list_medication_id) values(200,6,1)

insert into price_medications(price,medication_id,price_list_medication_id) values(220,1,2)
insert into price_medications(price,medication_id,price_list_medication_id) values(500,2,2)
insert into price_medications(price,medication_id,price_list_medication_id) values(450,3,2)
insert into price_medications(price,medication_id,price_list_medication_id) values(300,4,2)
insert into price_medications(price,medication_id,price_list_medication_id) values(200,5,2)
insert into price_medications(price,medication_id,price_list_medication_id) values(100,6,2)

insert into price_medications(price,medication_id,price_list_medication_id) values(220,1,3)
insert into price_medications(price,medication_id,price_list_medication_id) values(145,2,3)
insert into price_medications(price,medication_id,price_list_medication_id) values(130,3,3)
insert into price_medications(price,medication_id,price_list_medication_id) values(350,4,3)
insert into price_medications(price,medication_id,price_list_medication_id) values(235,5,3)
insert into price_medications(price,medication_id,price_list_medication_id) values(180,6,3)

insert into price_medications(price,medication_id,price_list_medication_id) values(220,1,4)
insert into price_medications(price,medication_id,price_list_medication_id) values(250,2,4)
insert into price_medications(price,medication_id,price_list_medication_id) values(260,3,4)
insert into price_medications(price,medication_id,price_list_medication_id) values(270,4,4)
insert into price_medications(price,medication_id,price_list_medication_id) values(280,5,4)
insert into price_medications(price,medication_id,price_list_medication_id) values(290,6,4)

insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,1,24)

insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,1,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (3,1,24)

insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,2,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (3,2,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,2,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (3,3,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,3,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,10,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (3,10,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,4,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,4,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,5,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (2,5,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,6,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,6,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,8,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,8,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (4,9,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (3,9,24)
insert into dermatologist_rating(rating,dermatologist_id,patient_id) values (5,10,24)

insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,12)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(3,24,12)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,13)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(4,24,13)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,14)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(2,24,14)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,15)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(2,24,15)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,16)
insert into pharmacist_ratings(rating,patient_id,pharmacist_id) values(5,24,16)

insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (5,24,1)
insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (4,23,1)
insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (5,25,1)

insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (5,24,2)
insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (4,23,2)
insert into pharmacy_rating(rating,patient_id,pharmacy_id) values (5,25,2)

insert into loyalty_program(bodovi, naziv, popust) values (30, 'Neki naziv', 23.4)

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id, loyalty_type_id, points) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic21@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null, 1, 5) 

insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id, loyalty_type_id, points) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic21@gmail.com', true, 'Milos', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null, 1, 40) 

insert into pharmacy_suppliers(pharmacy_id, supplier_id) values (1,47)

insert into purchase_order_list(endtime, starttime, purchase_status, pharmacy_administrator_id) values ('2021-06-13 14:00:00-08', '2021-06-13 07:00:00-08', 'CEKA_PONUDE', 43)

insert into purchase_order_list(endtime, purchase_status, starttime, pharmacy_administrator_id) values ('2021-11-11', 'CEKA_PONUDE', '2021-02-02', 44)
insert into medication_quantity_of_purchase_order(order_id, quantity, medication_id) values (1, 40, 1)
insert into medication_quantity_of_purchase_order(order_id, quantity, medication_id) values (1, 40, 2)
insert into medication_quantity_of_purchase_order(order_id, quantity, medication_id) values (1, 40, 3)

