insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Novi Sad', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 1')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Sabac', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 2')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Nis', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 3')
insert into pharmacies(city, number, postalcode, state, street, avg_rating, name) values ('Beograd', '11', 21241, 'Srbija', 'Stefana Nemanje', 9, 'Pharmacy 4')


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic1@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic2@gmail.com', true, 'Nemanja', 'kinzo','+381613238249', 'Tamic', 'DERMATOLOGIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic3@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Ivanovic', 'DERMATOLOGIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic4@gmail.com', true, 'Ana', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic5@gmail.com', true, 'Milica', 'kinzo','+381613238249', 'Antonic', 'DERMATOLOGIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic6@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Kesic', 'DERMATOLOGIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic7@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Lakic', 'DERMATOLOGIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic8@gmail.com', true, 'Mirjana', 'kinzo','+381613238249', 'Loncar', 'DERMATOLOGIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic9@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Vulin', 'DERMATOLOGIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Dermatologist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic10@gmail.com', true, 'Mirko', 'kinzo','+381613238249', 'Milinkovic', 'DERMATOLOGIST', null, 4)

insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,1)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,2)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (1,3)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,4)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,5)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (2,6)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,7)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,8)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (3,9)
insert into dermatologist_pharmacy(pharmacy_id, dermatologist_id) values (4,10)


insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic11@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic12@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic13@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 1)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic14@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic15@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic16@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 2)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic17@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic18@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic19@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 3)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Pharmacist', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic20@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PHARMACIST', null, 4)



insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Nikola', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Vuk', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Petar', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Perica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Milic', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Sandra', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Tamara', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Jovan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Jelena', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Jovana', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Nenad', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Katarina', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Dusan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Stevan', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Konjislav', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Boban', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Mikica', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Izet', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Farok', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)
insert into users(dtype, city, number, postalcode, state, street, email, is_first_time_logging, name, password, phone, surname, usertype, penalties, pharmacy_id) values ('Patient', 'Novi Sad', '23', 21241, 'Srbija', 'Stefana Nemanje', 'antonic@gmail.com', true, 'Radasin', 'kinzo','+381613238249', 'Antonic', 'PATIENT', 0, null)


insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Brufen', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Panklav', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Phlebodia', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Synthroid', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Crestor', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Nexium', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Abilify', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Crestor', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Lantus Solostar', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Advair Diskus', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Remicade', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Lisinopril', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Levothyroxine', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Metoprolol', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Omeprazole', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Simvastatin', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Losartan', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Albuterol', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Sirup', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')
insert into medications (code, contraindications, description, manufacturer, medication_form, name, prescription_regime, recommended_intake, structure, medication_type, pharmacy_id) values ('', '', '', '', 'PRASAK', 'Panklav', 'NA_RECEPT', '', '', 'ANTIPYRETIC', '1')


insert into medication_quantity (quantity, medication_id) values (9, 1)
insert into medication_quantity (quantity, medication_id) values (10, 1)
insert into medication_quantity (quantity, medication_id) values (9, 2)
insert into medication_quantity (quantity, medication_id) values (10, 2)
insert into medication_quantity (quantity, medication_id) values (9, 3)
insert into medication_quantity (quantity, medication_id) values (10, 3)
insert into medication_quantity (quantity, medication_id) values (9, 4)
insert into medication_quantity (quantity, medication_id) values (10, 4)
insert into medication_quantity (quantity, medication_id) values (9, 5)
insert into medication_quantity (quantity, medication_id) values (10, 5)
insert into medication_quantity (quantity, medication_id) values (9, 6)
insert into medication_quantity (quantity, medication_id) values (10, 6)
insert into medication_quantity (quantity, medication_id) values (9, 7)
insert into medication_quantity (quantity, medication_id) values (10, 7)
insert into medication_quantity (quantity, medication_id) values (9, 8)
insert into medication_quantity (quantity, medication_id) values (10, 8)
insert into medication_quantity (quantity, medication_id) values (9, 9)
insert into medication_quantity (quantity, medication_id) values (10, 9)
insert into medication_quantity (quantity, medication_id) values (9, 10)
insert into medication_quantity (quantity, medication_id) values (11, 10)
insert into medication_quantity (quantity, medication_id) values (9, 11)
insert into medication_quantity (quantity, medication_id) values (10, 11)
insert into medication_quantity (quantity, medication_id) values (9, 12)
insert into medication_quantity (quantity, medication_id) values (10, 12)
insert into medication_quantity (quantity, medication_id) values (9, 13)
insert into medication_quantity (quantity, medication_id) values (10, 13)
insert into medication_quantity (quantity, medication_id) values (9, 14)
insert into medication_quantity (quantity, medication_id) values (10, 14)
insert into medication_quantity (quantity, medication_id) values (9, 15)
insert into medication_quantity (quantity, medication_id) values (10, 15)
insert into medication_quantity (quantity, medication_id) values (9, 16)
insert into medication_quantity (quantity, medication_id) values (10, 16)
insert into medication_quantity (quantity, medication_id) values (10, 17)
insert into medication_quantity (quantity, medication_id) values (10, 18)
insert into medication_quantity (quantity, medication_id) values (10, 19)

insert into medication_quantity (quantity, medication_id) values (4, 1)
insert into medication_quantity (quantity, medication_id) values (4, 2)
insert into medication_quantity (quantity, medication_id) values (4, 3)
insert into medication_quantity (quantity, medication_id) values (4, 4)
insert into medication_quantity (quantity, medication_id) values (4, 5)
insert into medication_quantity (quantity, medication_id) values (4, 6)
insert into medication_quantity (quantity, medication_id) values (4, 7)
insert into medication_quantity (quantity, medication_id) values (4, 8)
insert into medication_quantity (quantity, medication_id) values (4, 9)
insert into medication_quantity (quantity, medication_id) values (4, 10)
insert into medication_quantity (quantity, medication_id) values (4, 11)
insert into medication_quantity (quantity, medication_id) values (4, 12)
insert into medication_quantity (quantity, medication_id) values (4, 13)

insert into patient_allerged_on_medications(patient_id, medication_id) values (1, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (1, 2)
insert into patient_allerged_on_medications(patient_id, medication_id) values (1, 3)
insert into patient_allerged_on_medications(patient_id, medication_id) values (1, 4)
insert into patient_allerged_on_medications(patient_id, medication_id) values (2, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (2, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (2, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (2, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (3, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (3, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (3, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (3, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (4, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (4, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (4, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (4, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (5, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (5, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (5, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (5, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (6, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (6, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (6, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (6, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (7, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (7, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (7, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (7, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (8, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (8, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (8, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (8, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (8, 9)
insert into patient_allerged_on_medications(patient_id, medication_id) values (9, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (9, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (9, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (9, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (9, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (10, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (10, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (10, 12)
insert into patient_allerged_on_medications(patient_id, medication_id) values (10, 13)
insert into patient_allerged_on_medications(patient_id, medication_id) values (11, 5)
insert into patient_allerged_on_medications(patient_id, medication_id) values (11, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (11, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (11, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (12, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (12, 2)
insert into patient_allerged_on_medications(patient_id, medication_id) values (12, 3)
insert into patient_allerged_on_medications(patient_id, medication_id) values (12, 4)
insert into patient_allerged_on_medications(patient_id, medication_id) values (13, 6)
insert into patient_allerged_on_medications(patient_id, medication_id) values (13, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (13, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (13, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (14, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (14, 16)
insert into patient_allerged_on_medications(patient_id, medication_id) values (14, 18)
insert into patient_allerged_on_medications(patient_id, medication_id) values (14, 19)
insert into patient_allerged_on_medications(patient_id, medication_id) values (15, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (15, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (15, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (15, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (16, 10)
insert into patient_allerged_on_medications(patient_id, medication_id) values (16, 11)
insert into patient_allerged_on_medications(patient_id, medication_id) values (16, 1)
insert into patient_allerged_on_medications(patient_id, medication_id) values (16, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (17, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (17, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (17, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (17, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (18, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (18, 8)
insert into patient_allerged_on_medications(patient_id, medication_id) values (18, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (18, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (19, 14)
insert into patient_allerged_on_medications(patient_id, medication_id) values (19, 15)
insert into patient_allerged_on_medications(patient_id, medication_id) values (19, 7)
insert into patient_allerged_on_medications(patient_id, medication_id) values (19, 8)


insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 21, 1)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 22, 1)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 23, 1)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 24, 2)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 25, 2)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 26, 2)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 27, 3)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 28, 3)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 29, 3)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 30, 4)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 31, 4)
insert into eprescription (is_used, endtime, starttime, patient_id, pharmacy_id) values (false, '2021-08-13 09:00:00-08', '2021-08-13 09:30:00-08', 32, 4)

insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,36)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,37)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,38)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,39)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,40)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,41)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,42)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,43)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,44)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,45)
insert into eprescription_prescribed_medications(eprescription_id, prescribed_medications_id) values (1,46)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (1,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (2,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (3,20)

insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,1)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,2)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,3)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,4)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,5)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,6)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,7)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,8)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,9)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,10)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,11)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,12)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,13)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,14)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,15)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,16)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,17)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,18)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,19)
insert into pharmacies_medication_quantity(pharmacy_id, medication_quantity_id) values (4,20)

insert into replacement_medications (medication_id, replacement_medication_id) values (1,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (1,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (1,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (1,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (2,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (2,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (2,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (3,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (3,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (3,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (3,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (4,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (4,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (4,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (5,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (5,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (5,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (5,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (6,4)
insert into replacement_medications (medication_id, replacement_medication_id) values (6,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (6,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (6,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (6,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (7,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (7,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (7,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (8,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (8,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (8,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (9,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (9,11)
insert into replacement_medications (medication_id, replacement_medication_id) values (9,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (10,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (10,1)
insert into replacement_medications (medication_id, replacement_medication_id) values (11,2)
insert into replacement_medications (medication_id, replacement_medication_id) values (11,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (11,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (11,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (12,14)
insert into replacement_medications (medication_id, replacement_medication_id) values (12,13)
insert into replacement_medications (medication_id, replacement_medication_id) values (12,16)
insert into replacement_medications (medication_id, replacement_medication_id) values (13,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (13,14)
insert into replacement_medications (medication_id, replacement_medication_id) values (13,18)
insert into replacement_medications (medication_id, replacement_medication_id) values (13,16)
insert into replacement_medications (medication_id, replacement_medication_id) values (14,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (14,1)
insert into replacement_medications (medication_id, replacement_medication_id) values (14,18)
insert into replacement_medications (medication_id, replacement_medication_id) values (14,16)
insert into replacement_medications (medication_id, replacement_medication_id) values (15,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (15,14)
insert into replacement_medications (medication_id, replacement_medication_id) values (15,18)
insert into replacement_medications (medication_id, replacement_medication_id) values (15,16)
insert into replacement_medications (medication_id, replacement_medication_id) values (16,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (16,7)
insert into replacement_medications (medication_id, replacement_medication_id) values (16,18)
insert into replacement_medications (medication_id, replacement_medication_id) values (16,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (17,7)
insert into replacement_medications (medication_id, replacement_medication_id) values (17,6)
insert into replacement_medications (medication_id, replacement_medication_id) values (17,10)
insert into replacement_medications (medication_id, replacement_medication_id) values (18,7)
insert into replacement_medications (medication_id, replacement_medication_id) values (18,13)
insert into replacement_medications (medication_id, replacement_medication_id) values (18,5)
insert into replacement_medications (medication_id, replacement_medication_id) values (19,7)
insert into replacement_medications (medication_id, replacement_medication_id) values (19,18)
insert into replacement_medications (medication_id, replacement_medication_id) values (19,5)

insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 1,21,1)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 2,22,1)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 3,23,1)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 4,24,1)

insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 5,25,2)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 6,26,2)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 7,27,2)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 8,28,2)

insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 9,29,3)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 10,30,3)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 11,31,3)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 12,32,3)

insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 13,33,4)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 14,34,4)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-21 00:00:00-08', 15,35,4)
insert into reservations (is_done, endtime, starttime, medication_id, patient_id, pharmacy_id) values (false, '2021-07-03 00:00:00-08', '2021-07-04 00:00:00-08', 16,36,4)

insert into appointments (is_finished, is_taken, endtime, starttime, report, dermatologist_id, patient_id, pharmacy_id) values (false, false, '2021-07-13 09:00:00-08', '2021-08-13 09:30:00-08', '', 1, 21, 1)

insert into consultations (is_finished, endtime, starttime, report, patient_id, pharmacist_id, pharmacy_id) values (false, '2021-07-13 09:00:00-08', '2021-07-13 09:30:00-08', '', 11, 22, 1)

insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 1)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 2)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 3)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 4)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 5)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 6)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 7)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 8)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 9)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 10)

insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 11)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 12)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 13)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 14)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 07:00:00-08', '2021-07-13 14:00:00-08', 15)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 16)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 17)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 18)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 19)
insert into workdays (endtime, starttime, user_id) values ('2021-07-13 14:00:00-08', '2021-07-13 22:00:00-08', 20)

